/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as GamingZonesRouteImport } from './routes/gaming-zones'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminAvailabilityViolationsRouteImport } from './routes/admin.availability-violations'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminOwnersRouteImport } from './routes/admin.owners'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTournamentsRouteImport } from './routes/admin.tournaments'
import { Route as AdminTurfRequestsRouteImport } from './routes/admin.turf-requests'
import { Route as AdminTurfsRouteImport } from './routes/admin.turfs'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as BookingTurfIdRouteImport } from './routes/booking.$turfId'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings.$bookingId'
import { Route as ConfirmationTurfIdRouteImport } from './routes/confirmation.$turfId'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as OwnerAddTurfRouteImport } from './routes/owner.add-turf'
import { Route as OwnerAiAssistantRouteImport } from './routes/owner.ai-assistant'
import { Route as OwnerAnalyticsRouteImport } from './routes/owner.analytics'
import { Route as OwnerAvailabilityRouteImport } from './routes/owner.availability'
import { Route as OwnerBookingsRouteImport } from './routes/owner.bookings'
import { Route as OwnerHelpRouteImport } from './routes/owner.help'
import { Route as OwnerNotificationsRouteImport } from './routes/owner.notifications'
import { Route as OwnerProfileRouteImport } from './routes/owner.profile'
import { Route as OwnerReviewsRouteImport } from './routes/owner.reviews'
import { Route as OwnerSlotsRouteImport } from './routes/owner.slots'
import { Route as OwnerTournamentsRouteImport } from './routes/owner.tournaments'
import { Route as OwnerTurfsRouteImport } from './routes/owner.turfs'
import { Route as OwnerVideosRouteImport } from './routes/owner.videos'
import { Route as TurfsTurfIdRouteImport } from './routes/turfs.$turfId'
import { Route as OwnerTurfsTurfIdEditRouteImport } from './routes/owner.turfs.$turfId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const GamingZonesRoute = GamingZonesRouteImport.update({
  id: '/gaming-zones',
  path: '/gaming-zones',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvailabilityViolationsRoute =
  AdminAvailabilityViolationsRouteImport.update({
    id: '/availability-violations',
    path: '/availability-violations',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOwnersRoute = AdminOwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTournamentsRoute = AdminTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTurfRequestsRoute = AdminTurfRequestsRouteImport.update({
  id: '/turf-requests',
  path: '/turf-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTurfsRoute = AdminTurfsRouteImport.update({
  id: '/turfs',
  path: '/turfs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const BookingTurfIdRoute = BookingTurfIdRouteImport.update({
  id: '/booking/$turfId',
  path: '/booking/$turfId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/$bookingId',
  path: '/$bookingId',
  getParentRoute: () => BookingsRoute,
} as any)
const ConfirmationTurfIdRoute = ConfirmationTurfIdRouteImport.update({
  id: '/confirmation/$turfId',
  path: '/confirmation/$turfId',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAddTurfRoute = OwnerAddTurfRouteImport.update({
  id: '/add-turf',
  path: '/add-turf',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAiAssistantRoute = OwnerAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAnalyticsRoute = OwnerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAvailabilityRoute = OwnerAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerBookingsRoute = OwnerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerHelpRoute = OwnerHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerNotificationsRoute = OwnerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerProfileRoute = OwnerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerReviewsRoute = OwnerReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSlotsRoute = OwnerSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerTournamentsRoute = OwnerTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerTurfsRoute = OwnerTurfsRouteImport.update({
  id: '/turfs',
  path: '/turfs',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerVideosRoute = OwnerVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => OwnerRoute,
} as any)
const TurfsTurfIdRoute = TurfsTurfIdRouteImport.update({
  id: '/turfs/$turfId',
  path: '/turfs/$turfId',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerTurfsTurfIdEditRoute = OwnerTurfsTurfIdEditRouteImport.update({
  id: '/$turfId/edit',
  path: '/$turfId/edit',
  getParentRoute: () => OwnerTurfsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRouteWithChildren
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/gaming-zones': typeof GamingZonesRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/notifications': typeof NotificationsRoute
  '/owner': typeof OwnerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/rewards': typeof RewardsRoute
  '/sports': typeof SportsRoute
  '/tournaments': typeof TournamentsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/availability-violations': typeof AdminAvailabilityViolationsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/owners': typeof AdminOwnersRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/admin/turf-requests': typeof AdminTurfRequestsRoute
  '/admin/turfs': typeof AdminTurfsRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/$turfId': typeof BookingTurfIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/confirmation/$turfId': typeof ConfirmationTurfIdRoute
  '/owner/add-turf': typeof OwnerAddTurfRoute
  '/owner/ai-assistant': typeof OwnerAiAssistantRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/availability': typeof OwnerAvailabilityRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/help': typeof OwnerHelpRoute
  '/owner/notifications': typeof OwnerNotificationsRoute
  '/owner/profile': typeof OwnerProfileRoute
  '/owner/reviews': typeof OwnerReviewsRoute
  '/owner/slots': typeof OwnerSlotsRoute
  '/owner/tournaments': typeof OwnerTournamentsRoute
  '/owner/turfs': typeof OwnerTurfsRouteWithChildren
  '/owner/videos': typeof OwnerVideosRoute
  '/turfs/$turfId': typeof TurfsTurfIdRoute
  '/admin/': typeof AdminIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/owner/turfs/$turfId/edit': typeof OwnerTurfsTurfIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/gaming-zones': typeof GamingZonesRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/rewards': typeof RewardsRoute
  '/sports': typeof SportsRoute
  '/tournaments': typeof TournamentsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/availability-violations': typeof AdminAvailabilityViolationsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/owners': typeof AdminOwnersRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/admin/turf-requests': typeof AdminTurfRequestsRoute
  '/admin/turfs': typeof AdminTurfsRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/$turfId': typeof BookingTurfIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/confirmation/$turfId': typeof ConfirmationTurfIdRoute
  '/owner/add-turf': typeof OwnerAddTurfRoute
  '/owner/ai-assistant': typeof OwnerAiAssistantRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/availability': typeof OwnerAvailabilityRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/help': typeof OwnerHelpRoute
  '/owner/notifications': typeof OwnerNotificationsRoute
  '/owner/profile': typeof OwnerProfileRoute
  '/owner/reviews': typeof OwnerReviewsRoute
  '/owner/slots': typeof OwnerSlotsRoute
  '/owner/tournaments': typeof OwnerTournamentsRoute
  '/owner/turfs': typeof OwnerTurfsRouteWithChildren
  '/owner/videos': typeof OwnerVideosRoute
  '/turfs/$turfId': typeof TurfsTurfIdRoute
  '/admin': typeof AdminIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/owner/turfs/$turfId/edit': typeof OwnerTurfsTurfIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRouteWithChildren
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/gaming-zones': typeof GamingZonesRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/notifications': typeof NotificationsRoute
  '/owner': typeof OwnerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/rewards': typeof RewardsRoute
  '/sports': typeof SportsRoute
  '/tournaments': typeof TournamentsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/availability-violations': typeof AdminAvailabilityViolationsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/owners': typeof AdminOwnersRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/admin/turf-requests': typeof AdminTurfRequestsRoute
  '/admin/turfs': typeof AdminTurfsRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/$turfId': typeof BookingTurfIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/confirmation/$turfId': typeof ConfirmationTurfIdRoute
  '/owner/add-turf': typeof OwnerAddTurfRoute
  '/owner/ai-assistant': typeof OwnerAiAssistantRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/availability': typeof OwnerAvailabilityRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/help': typeof OwnerHelpRoute
  '/owner/notifications': typeof OwnerNotificationsRoute
  '/owner/profile': typeof OwnerProfileRoute
  '/owner/reviews': typeof OwnerReviewsRoute
  '/owner/slots': typeof OwnerSlotsRoute
  '/owner/tournaments': typeof OwnerTournamentsRoute
  '/owner/turfs': typeof OwnerTurfsRouteWithChildren
  '/owner/videos': typeof OwnerVideosRoute
  '/turfs/$turfId': typeof TurfsTurfIdRoute
  '/admin/': typeof AdminIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/owner/turfs/$turfId/edit': typeof OwnerTurfsTurfIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bookings'
    | '/explore'
    | '/favorites'
    | '/gaming-zones'
    | '/help'
    | '/login'
    | '/membership'
    | '/notifications'
    | '/owner'
    | '/profile'
    | '/register'
    | '/rewards'
    | '/sports'
    | '/tournaments'
    | '/admin/audit-logs'
    | '/admin/availability-violations'
    | '/admin/bookings'
    | '/admin/disputes'
    | '/admin/notifications'
    | '/admin/owners'
    | '/admin/revenue'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/tournaments'
    | '/admin/turf-requests'
    | '/admin/turfs'
    | '/admin/users'
    | '/booking/$turfId'
    | '/bookings/$bookingId'
    | '/confirmation/$turfId'
    | '/owner/add-turf'
    | '/owner/ai-assistant'
    | '/owner/analytics'
    | '/owner/availability'
    | '/owner/bookings'
    | '/owner/help'
    | '/owner/notifications'
    | '/owner/profile'
    | '/owner/reviews'
    | '/owner/slots'
    | '/owner/tournaments'
    | '/owner/turfs'
    | '/owner/videos'
    | '/turfs/$turfId'
    | '/admin/'
    | '/owner/'
    | '/owner/turfs/$turfId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/explore'
    | '/favorites'
    | '/gaming-zones'
    | '/help'
    | '/login'
    | '/membership'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/rewards'
    | '/sports'
    | '/tournaments'
    | '/admin/audit-logs'
    | '/admin/availability-violations'
    | '/admin/bookings'
    | '/admin/disputes'
    | '/admin/notifications'
    | '/admin/owners'
    | '/admin/revenue'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/tournaments'
    | '/admin/turf-requests'
    | '/admin/turfs'
    | '/admin/users'
    | '/booking/$turfId'
    | '/bookings/$bookingId'
    | '/confirmation/$turfId'
    | '/owner/add-turf'
    | '/owner/ai-assistant'
    | '/owner/analytics'
    | '/owner/availability'
    | '/owner/bookings'
    | '/owner/help'
    | '/owner/notifications'
    | '/owner/profile'
    | '/owner/reviews'
    | '/owner/slots'
    | '/owner/tournaments'
    | '/owner/turfs'
    | '/owner/videos'
    | '/turfs/$turfId'
    | '/admin'
    | '/owner'
    | '/owner/turfs/$turfId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bookings'
    | '/explore'
    | '/favorites'
    | '/gaming-zones'
    | '/help'
    | '/login'
    | '/membership'
    | '/notifications'
    | '/owner'
    | '/profile'
    | '/register'
    | '/rewards'
    | '/sports'
    | '/tournaments'
    | '/admin/audit-logs'
    | '/admin/availability-violations'
    | '/admin/bookings'
    | '/admin/disputes'
    | '/admin/notifications'
    | '/admin/owners'
    | '/admin/revenue'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/tournaments'
    | '/admin/turf-requests'
    | '/admin/turfs'
    | '/admin/users'
    | '/booking/$turfId'
    | '/bookings/$bookingId'
    | '/confirmation/$turfId'
    | '/owner/add-turf'
    | '/owner/ai-assistant'
    | '/owner/analytics'
    | '/owner/availability'
    | '/owner/bookings'
    | '/owner/help'
    | '/owner/notifications'
    | '/owner/profile'
    | '/owner/reviews'
    | '/owner/slots'
    | '/owner/tournaments'
    | '/owner/turfs'
    | '/owner/videos'
    | '/turfs/$turfId'
    | '/admin/'
    | '/owner/'
    | '/owner/turfs/$turfId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingsRoute: typeof BookingsRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  FavoritesRoute: typeof FavoritesRoute
  GamingZonesRoute: typeof GamingZonesRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  MembershipRoute: typeof MembershipRoute
  NotificationsRoute: typeof NotificationsRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RewardsRoute: typeof RewardsRoute
  SportsRoute: typeof SportsRoute
  TournamentsRoute: typeof TournamentsRoute
  BookingTurfIdRoute: typeof BookingTurfIdRoute
  ConfirmationTurfIdRoute: typeof ConfirmationTurfIdRoute
  TurfsTurfIdRoute: typeof TurfsTurfIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaming-zones': {
      id: '/gaming-zones'
      path: '/gaming-zones'
      fullPath: '/gaming-zones'
      preLoaderRoute: typeof GamingZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/availability-violations': {
      id: '/admin/availability-violations'
      path: '/availability-violations'
      fullPath: '/admin/availability-violations'
      preLoaderRoute: typeof AdminAvailabilityViolationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/owners': {
      id: '/admin/owners'
      path: '/owners'
      fullPath: '/admin/owners'
      preLoaderRoute: typeof AdminOwnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tournaments': {
      id: '/admin/tournaments'
      path: '/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AdminTournamentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/turf-requests': {
      id: '/admin/turf-requests'
      path: '/turf-requests'
      fullPath: '/admin/turf-requests'
      preLoaderRoute: typeof AdminTurfRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/turfs': {
      id: '/admin/turfs'
      path: '/turfs'
      fullPath: '/admin/turfs'
      preLoaderRoute: typeof AdminTurfsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/booking/$turfId': {
      id: '/booking/$turfId'
      path: '/booking/$turfId'
      fullPath: '/booking/$turfId'
      preLoaderRoute: typeof BookingTurfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/confirmation/$turfId': {
      id: '/confirmation/$turfId'
      path: '/confirmation/$turfId'
      fullPath: '/confirmation/$turfId'
      preLoaderRoute: typeof ConfirmationTurfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/add-turf': {
      id: '/owner/add-turf'
      path: '/add-turf'
      fullPath: '/owner/add-turf'
      preLoaderRoute: typeof OwnerAddTurfRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/ai-assistant': {
      id: '/owner/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/owner/ai-assistant'
      preLoaderRoute: typeof OwnerAiAssistantRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/analytics': {
      id: '/owner/analytics'
      path: '/analytics'
      fullPath: '/owner/analytics'
      preLoaderRoute: typeof OwnerAnalyticsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/availability': {
      id: '/owner/availability'
      path: '/availability'
      fullPath: '/owner/availability'
      preLoaderRoute: typeof OwnerAvailabilityRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/bookings': {
      id: '/owner/bookings'
      path: '/bookings'
      fullPath: '/owner/bookings'
      preLoaderRoute: typeof OwnerBookingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/help': {
      id: '/owner/help'
      path: '/help'
      fullPath: '/owner/help'
      preLoaderRoute: typeof OwnerHelpRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/notifications': {
      id: '/owner/notifications'
      path: '/notifications'
      fullPath: '/owner/notifications'
      preLoaderRoute: typeof OwnerNotificationsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/profile': {
      id: '/owner/profile'
      path: '/profile'
      fullPath: '/owner/profile'
      preLoaderRoute: typeof OwnerProfileRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/reviews': {
      id: '/owner/reviews'
      path: '/reviews'
      fullPath: '/owner/reviews'
      preLoaderRoute: typeof OwnerReviewsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/slots': {
      id: '/owner/slots'
      path: '/slots'
      fullPath: '/owner/slots'
      preLoaderRoute: typeof OwnerSlotsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/tournaments': {
      id: '/owner/tournaments'
      path: '/tournaments'
      fullPath: '/owner/tournaments'
      preLoaderRoute: typeof OwnerTournamentsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/turfs': {
      id: '/owner/turfs'
      path: '/turfs'
      fullPath: '/owner/turfs'
      preLoaderRoute: typeof OwnerTurfsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/videos': {
      id: '/owner/videos'
      path: '/videos'
      fullPath: '/owner/videos'
      preLoaderRoute: typeof OwnerVideosRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/turfs/$turfId': {
      id: '/turfs/$turfId'
      path: '/turfs/$turfId'
      fullPath: '/turfs/$turfId'
      preLoaderRoute: typeof TurfsTurfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/turfs/$turfId/edit': {
      id: '/owner/turfs/$turfId/edit'
      path: '/$turfId/edit'
      fullPath: '/owner/turfs/$turfId/edit'
      preLoaderRoute: typeof OwnerTurfsTurfIdEditRouteImport
      parentRoute: typeof OwnerTurfsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminAvailabilityViolationsRoute: typeof AdminAvailabilityViolationsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOwnersRoute: typeof AdminOwnersRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTournamentsRoute: typeof AdminTournamentsRoute
  AdminTurfRequestsRoute: typeof AdminTurfRequestsRoute
  AdminTurfsRoute: typeof AdminTurfsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminAvailabilityViolationsRoute: AdminAvailabilityViolationsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOwnersRoute: AdminOwnersRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTournamentsRoute: AdminTournamentsRoute,
  AdminTurfRequestsRoute: AdminTurfRequestsRoute,
  AdminTurfsRoute: AdminTurfsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BookingsRouteChildren {
  BookingsBookingIdRoute: typeof BookingsBookingIdRoute
}

const BookingsRouteChildren: BookingsRouteChildren = {
  BookingsBookingIdRoute: BookingsBookingIdRoute,
}

const BookingsRouteWithChildren = BookingsRoute._addFileChildren(
  BookingsRouteChildren,
)

interface OwnerTurfsRouteChildren {
  OwnerTurfsTurfIdEditRoute: typeof OwnerTurfsTurfIdEditRoute
}

const OwnerTurfsRouteChildren: OwnerTurfsRouteChildren = {
  OwnerTurfsTurfIdEditRoute: OwnerTurfsTurfIdEditRoute,
}

const OwnerTurfsRouteWithChildren = OwnerTurfsRoute._addFileChildren(
  OwnerTurfsRouteChildren,
)

interface OwnerRouteChildren {
  OwnerAddTurfRoute: typeof OwnerAddTurfRoute
  OwnerAiAssistantRoute: typeof OwnerAiAssistantRoute
  OwnerAnalyticsRoute: typeof OwnerAnalyticsRoute
  OwnerAvailabilityRoute: typeof OwnerAvailabilityRoute
  OwnerBookingsRoute: typeof OwnerBookingsRoute
  OwnerHelpRoute: typeof OwnerHelpRoute
  OwnerNotificationsRoute: typeof OwnerNotificationsRoute
  OwnerProfileRoute: typeof OwnerProfileRoute
  OwnerReviewsRoute: typeof OwnerReviewsRoute
  OwnerSlotsRoute: typeof OwnerSlotsRoute
  OwnerTournamentsRoute: typeof OwnerTournamentsRoute
  OwnerTurfsRoute: typeof OwnerTurfsRouteWithChildren
  OwnerVideosRoute: typeof OwnerVideosRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerAddTurfRoute: OwnerAddTurfRoute,
  OwnerAiAssistantRoute: OwnerAiAssistantRoute,
  OwnerAnalyticsRoute: OwnerAnalyticsRoute,
  OwnerAvailabilityRoute: OwnerAvailabilityRoute,
  OwnerBookingsRoute: OwnerBookingsRoute,
  OwnerHelpRoute: OwnerHelpRoute,
  OwnerNotificationsRoute: OwnerNotificationsRoute,
  OwnerProfileRoute: OwnerProfileRoute,
  OwnerReviewsRoute: OwnerReviewsRoute,
  OwnerSlotsRoute: OwnerSlotsRoute,
  OwnerTournamentsRoute: OwnerTournamentsRoute,
  OwnerTurfsRoute: OwnerTurfsRouteWithChildren,
  OwnerVideosRoute: OwnerVideosRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingsRoute: BookingsRouteWithChildren,
  ExploreRoute: ExploreRoute,
  FavoritesRoute: FavoritesRoute,
  GamingZonesRoute: GamingZonesRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  MembershipRoute: MembershipRoute,
  NotificationsRoute: NotificationsRoute,
  OwnerRoute: OwnerRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RewardsRoute: RewardsRoute,
  SportsRoute: SportsRoute,
  TournamentsRoute: TournamentsRoute,
  BookingTurfIdRoute: BookingTurfIdRoute,
  ConfirmationTurfIdRoute: ConfirmationTurfIdRoute,
  TurfsTurfIdRoute: TurfsTurfIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
